package com.lambdaschool.foundation.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * The entity allowing interaction with the plants table.
 */
@Entity
@Table(name = "plants")
public class Plants
        extends Auditable
{
    /**
     * The primary key (long) of the plants table.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long plantid;

    /**
     * The nickname (String) of the plant. Cannot be null and must be unique.
     */
    @NotNull
    @Column(unique = true)
    private String nickname;

    /**
     * The species (String) of the plant. Cannot be null.
     */

    @NotNull
    private String species;

    /**
     * The Frequency of watering ex: "Monthly, Biweekly, weekly" (String) of the plant. Cannot be null.
     */

    @NotNull
    private String frequency;

    /**
     * The days of which watering is required "Monday - Sunday" (String) of the plant. Can be null if watering is set to daily.
     */

    private String days;

    /**
     * Image of plant, this is optional
     */

    private String image;

    /**
     * Description of plant Can be null.
     */

    private String description;

    /**
     * Date planted Cannot be null.
     */

    private String datePlanted;

    /**
     * special care instructions (optional).
     */

    private String careInstructions;


    /**
     * Forms a Many to One relationship between plants and users.
     * A user can have many plants.
     */
    @ManyToOne
    @NotNull
    @JoinColumn(name = "userid")
    @JsonIgnoreProperties(value = "plants",
            allowSetters = true)
    private User user;


    /**
     * default constructor
     */

    public Plants()
    {
    }

    /**
     * Given the params, create a new plant object
     * <p>
     * plantid is autogenerated
     *
     * @param nickname     The username (String) of the plant
     * @param species     The password (String) of the plant
     * @param frequency The water frequency (String) of the plant
     * @param days The days of the week which plant needs to be watered (String)
     * @param image optional if you want to add an image to your plant
     * @param description description of plant (String)
     * @param datePlanted when plant was planted (String)
     * @param careInstructions optional if you want to add anything else (String)
     * @param user The user to which the plants belong (User)
     */

    public Plants(@NotNull String nickname, @NotNull String species, @NotNull String frequency, String days, String image, String description, String datePlanted, String careInstructions, @NotNull User user) {
        this.nickname = nickname;
        this.species = species;
        this.frequency = frequency;
        this.days = days;
        this.image = image;
        this.description = description;
        this.datePlanted = datePlanted;
        this.careInstructions = careInstructions;
        this.user = user;
    }

    /**
     * Getters and Setters
     */

    public long getPlantid() {
        return plantid;
    }

    public void setPlantid(long plantid) {
        this.plantid = plantid;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getSpecies() {
        return species;
    }

    public void setSpecies(String species) {
        this.species = species;
    }

    public String getFrequency() {
        return frequency;
    }

    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }

    public String getDays() {
        return days;
    }

    public void setDays(String days) {
        this.days = days;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDatePlanted() {
        return datePlanted;
    }

    public void setDatePlanted(String datePlanted) {
        this.datePlanted = datePlanted;
    }

    public String getCareInstructions() {
        return careInstructions;
    }

    public void setCareInstructions(String careInstructions) {
        this.careInstructions = careInstructions;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}

